const ADD_TODO = "ADD_TODO";
const REMOVE_TODO = "REMOVE_TODO";
const UPDATE_ERRORS = "UPDATE_ERRORS";
const SET_TODO_VALUE = "SET_TODO_VALUE";
export { ADD_TODO, REMOVE_TODO, UPDATE_ERRORS, SET_TODO_VALUE };
